name: movies_app
description: "Test yo me animo"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^8.1.3
  dio: ^5.4.3+1
  injectable: ^2.4.0
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  copy_with_extension: ^5.0.4
  pull_to_refresh_plus: ^2.0.3
  flutter_screenutil: ^5.9.1
  flutter_smart_dialog: ^4.9.6+2
  pretty_dio_logger: ^1.3.1
  flutter_cache_manager: ^3.3.2
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.1
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  flutter_native_splash: ^2.4.0
  double_back_to_close_app: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  copy_with_extension_gen: ^5.0.4
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
